project_id = "your_project_id"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54327
file_size_limit = "50MiB"

[auth]
enabled = true
port = 54328
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://localhost:3000"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
security_refresh_token_reuse_interval = 10

[edge-runtime]
enabled = true
port = 54329

[functions.chat-with-ai]
verify_jwt = false

[functions.community-ai-assistant]
verify_jwt = false

[functions.get-openrouter-models]
verify_jwt = false

[functions.identify-plant]
verify_jwt = false

[functions.market-prices]
verify_jwt = false

[functions.notifications]
verify_jwt = false

[functions.weather-data]
verify_jwt = false

[functions.voice-chat-ai]
verify_jwt = false

[functions.test-openrouter]
verify_jwt = false

[functions.openrouter-direct]
verify_jwt = false

[functions.groq-ai-chat]
verify_jwt = false

